### PR TITLE
add info about custom SSL/TLS certificate and key

### PR DESCRIPTION
**Pull request by macbookandrew**
Thanks to a note by @markwoon on [this issue](https://github.com/BrowserSync/browser-sync/issues/193)

### CODE REVIEW

**Comment by shakyShane** [comment]
Hi, thanks for the PR

This site is auto-generated however, so your changes actually need to be in this file https://github.com/BrowserSync/browsersync.github.io/blob/master/_src/_includes/snippets/options/https.js

Then, run `npm install` followed by `npm run build`

**Comment by macbookandrew** [comment]
Here’s the change, though the build looks goofed up…not sure what’s wrong, since I’ve not used crossbow before.

**Comment by shakyShane** [comment]
Arg! Yes I've broken the builds in a recent change. I'll sort this ASAP. Thanks for your patience

**Comment by thejohnfreeman** [comment]
So there's a way to set these options in a call from, say, `gulpfile.js`, but not from the command line?

**Pull request closed without merging**
