### PR TITLE
add missing 'browserSync'

### PR DESCRIPTION
**Pull request by lookfirst**

### CODE REVIEW

**Comment by shinnn** [comment]
@lookfirst opened a new PR: #22

**Comment by lookfirst** [comment]
Two different PR's. Look more closely. =)

**Comment by lookfirst** [comment]
@shinnn please re-open and merge it. =)

**Comment by shinnn** [comment]
Ahhhhhhhhhhhh my bad :sob: 

The clearer title and detailed description in the first comment is more appreciated though.

**Comment by lookfirst** [comment]
Sure, I'll try harder next time. =) I'm just busy in the middle of 50 other things right now, so I apologize for being so brief!

**Comment by shakyShane** [comment]
fixed in 647c462c09ad371809bd70b81f710996a3823ca4 - Sorry I missed this PR

**Pull request closed without merging**
