### PR TITLE
Fix 'codeSync' example in docs.

### PR DESCRIPTION
**Pull request by mateatslc**
Switched from 'true' to 'false', also removed extra comma.

### CODE REVIEW

**Comment by shakyShane** [comment]
@mateatslc - thanks for the fix, but you need to apply it to [this file](https://github.com/mateatslc/browsersync.github.io/blob/master/_src/_includes/snippets/options/codeSync.js) instead as the website is auto generated.

Then simply follow the instructions in the readme.md to create the final site :)

**Comment by mateatslc** [comment]
@shakyShane - Hah, Crossbow was new to me. Sorry for not the reading instructions.

The weird thing is that build generates apparently unrelated changes in docs/api/index.html and docs/options/index.html too. I see things like 'sockets' and 'scrollRestoeTechnique' being added.
Could that be an earlier change without the generated files checked in properly?

**Comment by mateatslc** [comment]
few more commits to get this right:
- reverted my wrong fix
- 2nd commit shows those "unrelated changes" I was talking about:
https://github.com/mateatslc/browsersync.github.io/commit/efd9840c2ff99c720e5c42d0bf67197a37b35d6c
- the real fix for current PR

**Comment by shakyShane** [comment]
Sorry for missing this.

Actually, when you did a build the first time it was also updating some other areas that needed doing too, so anyway I've [commited](https://github.com/BrowserSync/browsersync.github.io/commit/710e461ffc2bce3c7ce292949ef38224e04ba846) in your name to save you having to amend this PR

Thanks again and sorry for letting this one slip through.

**Pull request closed without merging**
