### PR TITLE
Add missing next callback in proxy documentation

### PR DESCRIPTION
**Pull request by danieldiekmeier**
If you tried to execute the code snippet I changed, it would throw `ReferenceError: next is not defined`.

### CODE REVIEW

**Comment by shakyShane** [comment]
Excellent - thank you very much :)

**Comment by danieldiekmeier** [comment]
I'm sorry, there seems to be some other problem. I'll open an issue.

**Comment by shakyShane** [comment]
cool, thanks - I will release at some point tomorrow, so feel free to comb the site for erros :)

**Comment by danieldiekmeier** [comment]
See here: https://github.com/BrowserSync/browser-sync/issues/1019

**Pull request merged**
